### ISSUE TITLE
Using sunlinsol to solve a linear system

### ISSUE THREAD

**Issue by appolloford** [LLNL/sundials#140]
Hi,

I am trying to use `sunlinsol` to solve a linear system.

In the following code. I tried to generate a matrix `A = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]` and a vector `b = [1, 2, 3]` and then solve `Ar = b`. I expected to get the solution `r = [1, 1, 1]`, but I got `r = [3, 1/2, 2/3]`. It seems there is a shift in the index but I am not sure why. Do I set something wrong? Could anyone explain the steps behind `SUNLinSolSolve`?

```cpp
#include <nvector/nvector_serial.h>     // access to serial N_Vector
#include <sunlinsol/sunlinsol_dense.h>  // access to dense SUNLinearSolver

#define Ith(v,i)                 NV_Ith_S(v,i)
#define IJth(A, i, j)            SM_ELEMENT_D(A, i, j)

int main() {

    N_Vector b = N_VNew_Serial(3);
    N_Vector r = N_VNew_Serial(3);
    SUNMatrix A = SUNDenseMatrix(3, 3);

    N_VConst(0.0, r);
    for (int i=0; i<3; i++) {
        Ith(b, i) = i * 1.0 + 1.0;
        printf("Ith(b, %d) = %13.7e \n", i, Ith(b, i));
    }

    // IJth(A, 0, 0) = 1.0;
    // IJth(A, 0, 1) = 0.0;
    // IJth(A, 0, 2) = 0.0;
    // IJth(A, 1, 0) = 0.0;
    // IJth(A, 1, 1) = 2.0;
    // IJth(A, 1, 2) = 0.0;
    // IJth(A, 2, 0) = 0.0;
    // IJth(A, 2, 1) = 0.0;
    // IJth(A, 2, 2) = 3.0;

    for (int j=0; j<3; j++) {
        realtype *colj = SUNDenseMatrix_Column(A, j);
        for (int k=0; k<3; k++) {
            colj[k] = 0.0;
            if  (j == k) {
                colj[k] = k * 1.0 + 1.0;
            }
        }
    }


    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            printf("%13.7e ", IJth(A, i, j));
        }
        printf("\n");
    }

    SUNLinearSolver LS = SUNLinSol_Dense(r, A);

    int flag = SUNLinSolSolve(LS, A, r, b, 0.0);

    double *rptr = N_VGetArrayPointer(r);
    double *bptr = N_VGetArrayPointer(b);

    for (int i = 0; i < 3; i++) {
        printf("rptr[%d] = %13.7e\n", i, rptr[i]);
    }

    return 0;

}
```

The output:
```
Ith(b, 0) = 1.0000000e+00
Ith(b, 1) = 2.0000000e+00
Ith(b, 2) = 3.0000000e+00
1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 2.0000000e+00 0.0000000e+00
0.0000000e+00 0.0000000e+00 3.0000000e+00
rptr[0] = 3.0000000e+00
rptr[1] = 5.0000000e-01
rptr[2] = 6.6666667e-01
```

I have tested `sundials v.5.7.0` on `ubuntu18.04` and `sundials v.5.8.0` on `macos`.

I will be grateful for any help.

**Comment by drreynolds** [comment]
You are missing a call to `SUNLinSolSetup` just prior to your call to `SUNLinSolSolve`:
```
...
int flag = SUNLinSolSetup(LS, A);
flag = SUNLinSolSolve(LS, A, r, b, 0.0);
...
```

**Explanation:**
All of SUNDIALS' direct linear solvers must be operated in two phases: (a) the *setup* phase performs the LU factorization of the matrix, storing these factors in-place within the existing SUNMatrix object, and (b) the *solve* phase that uses these LU factors to solve a linear system.  This structure is in place because we strive to reuse the [costly] factorization across many solves to maximize computational efficiency.

In your example code, `SUNLinSolSolve` had to assume that your matrix `A` already contained the LU factorization of the original matrix, and it used those factors in its solve.

**Comment by appolloford** [comment]
Thank you for the help!!
