### ISSUE TITLE
Unintuitive behavior of USE_GENERIC_MATH

### ISSUE THREAD

**Issue by Steven-Roberts** [LLNL/sundials#149]
By default, `USE_GENERIC_MATH` is enabled which means when `SUNDIALS_PRECISION` is single or extended, values are still converted to doubles in math functions.  It is not well documented that `USE_GENERIC_MATH` should be disabled to use the math function particular to the precision.  One solution is to set the default value to off or base it on the C standard.

**Comment by balos1** [comment]
This is a great point @Steven-Roberts. I think we should do two things:

1. Just use the variant which matches `SUNDIALS_PRECISION` when the language standard is C99 or newer regardless of the value of `USE_GENERIC_MATH` since in C99 the standard math library has the float and long double variants. It does not seem to make sense to exclusively use the double versions when the others are available. 
2. Default to `USE_GENERIC_MATH=OFF` unless the standard is C89. We can document that in C89 the math functions will default to double precision unless generic math is turned off.

**Comment by drreynolds** [comment]
Thanks @Steven-Roberts for digging into this.  Even after all these years, there are a number of places in SUNDIALS where I still haven't ventured thoroughly.
