### ISSUE TITLE
Band preconditioning

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#172]
Hello,

Why band preconditioning is only available with CVODE and ARKODE ? 

S.

**Comment by drreynolds** [comment]
Since CVODE and ARKODE focus on ODE IVPs, e.g., $\dot{y}(t) = f(t,y(t))$, then the corresponding root-finding problems have Jacobians with the form $A = I - \gamma J$.  Due to the diagonal "$I$" matrix and the fact that $\gamma$ is proportional to the [typically small] time step size, then for some problems $A$ may be well-approximated by a banded (or banded block-diagonal) matrix.

IDA(S) and KINSOL, on the other hand, are formulated for more generic DAE and nonlinear systems defined by the residual functions $F(t,y,\dot{y})$ and $F(u)$, respectively, thus there is no guarantee that their root-finding problems will have Jacobians that can be at all approximated by a banded matrix (even for small step sizes with IDA).  Thus, we did not dedicate the effort to build band preconditioners for the other solvers.  That said, the code for the CVODE and ARKODE banded preconditioners is not overly complicated, so if you believe that a similar banded preconditioner would be relevant for your application with IDA(S) or KINSOL, then you should be able to replicate something similar.

**Comment by mottelet** [comment]
Got it, thanks. I suppose that when the actual system matrix is banded in the F(u) or F(t,yydot) case, then a band preconditionner with a bandwidth lower than the true bandwidth is useless right ?

**Comment by drreynolds** [comment]
I would not go so far as to say that.  If the lower-bandwidth approximation contains "sufficient" information from the Jacobian so that the preconditioned matrix is well-conditioned, then it could be effective.  I'll note that these banded preconditioners for CVODE and ARKODE are typically used on problems where the true Jacobian bandwidth exceeds the preconditioner bandwidth; their effectiveness in such situations is rather problem-dependent.

**Comment by mottelet** [comment]
> I would not go so far as to say that. If the lower-bandwidth approximation contains "sufficient" information from the Jacobian so that the preconditioned matrix is well-conditioned, then it could be effective. I'll note that these banded preconditioners for CVODE and ARKODE are typically used on problems where the true Jacobian bandwidth exceeds the preconditioner bandwidth; their effectiveness in such situations is rather problem-dependent.

Yes, this is particularly impressive on the cvDiurnal_kry_bp.c example (I tested it with MX=MY=100).
