### ISSUE TITLE
Email list no longer works

### ISSUE THREAD

**Issue by idontgetoutmuch** [LLNL/sundials#18]
I just posted to `sundials-users-request@listserv.llnl.gov` and got a message back

To cut  down on spam,  the SUNDIALS-USERS list  has been configured  to request
positive confirmation of messages posted to the SUNDIALS-USERS-request address.
You must now  confirm that the enclosed  message did originate from  you. To do
so, simply reply to  the present message and type "OK"  (without the quotes) in
the text of your message, or click on the link below. If this does not work, or
if the  message did  not originate from  you, then contact  the list  owner for
assistance.

To APPROVE the message:
http://listserv.llnl.gov/SCRIPTS/wa.exe?OK=FE2ECB38&L=SUNDIALS-USERS

But if I click on the link it times out.

**Comment by idontgetoutmuch** [comment]
![image](https://user-images.githubusercontent.com/1550265/60828730-14165c00-a1ab-11e9-8cb1-848abbfaa0b5.png)

**Comment by balos1** [comment]
The mailing list is still functioning properly. The link does not work because it is an internal domain - you would need to send the "OK" response instead. Also, the address `sundials-users-request@listserv.llnl.gov` is the alias that expands to the list owners. I think you probably want to send your question to `sundials-users@llnl.gov` instead.
