### ISSUE TITLE
ARKodeButcherTable_CheckOrder and tableau type

### ISSUE THREAD

**Issue by mottelet** [LLNL/sundials#195]
Hello,

Does ARKodeButcherTable_CheckOrder check wheter the tableau is actually of ERK or DIRK type ? 

S.

**Comment by drreynolds** [comment]
Hi @mottelet,

No, `ARKodeButcherTable_CheckOrder` does not check the type of table (in fact, the routine should also work correctly for fully implicit Runge--Kutta methods).  

I'll note that ARKODE does not use this function internally; it is designed as a user-callable utility routine.  We include it in the library so that we can easily verify new Butcher tables we add to ARKODE.

**Comment by mottelet** [comment]
OK. I saw that the check is done by ARKStepSetTables.

**Comment by mottelet** [comment]
OK. Maybe this should be precised, because in the actual version of the documentation of ARKStepSetTables(), it is said that "Error checking is performed on Bi and Be (if non-NULL) **to ensure that they specify DIRK and ERK methods**, respectively."

**Comment by drreynolds** [comment]
I'm not sure that I understand your request, @mottelet.  Although `ARKStepSetTables` does not immediately check that the inputs `Bi` and `Be` are lower-triangular and strictly-lower-triangular, respectively, those compatibility checks are indeed performed by ARKStep soon thereafter.  Since this is the one routine where users can manually specify the tables, the documentation for this function should indeed mention that the tables will be checked for compatibility.

Are you asking that the documentation for `ARKStepSetTables` include extra detail to explain that although it does not check for DIRK and ERK structure itself, this check is performed soon afterwards by ARKStep?  If that is your request, can you explain why you believe it is necessary to complicate the documentation in this way?  As I see it, there is little difference to users *where* this check is performed.

**Comment by mottelet** [comment]
No. Just change "to ensure that they specify DIRK and ERK methods, respectively" by something more close to the type of verification the function does (which does not include the matrix structure test).
