### ISSUE TITLE
Correct usage of SUNContext_Free

### ISSUE THREAD

**Issue by aragilar** [LLNL/sundials#233]
From https://sundials.readthedocs.io/en/latest/sundials/SUNContext_link.html#c.SUNContext_Free it seems that freeing the context can fail according to the docs (looking at the code, 0 is always returned). If the return value were to be non-zero, what are users supposed to do (e.g. retry freeing at some later point, leak the memory)? This differs from https://sundials.readthedocs.io/en/latest/cvode/Usage/index.html#c.CVodeFree and from the normal POSIX `free`, both of which do not return a status code.

**Comment by drreynolds** [comment]
I'd like to hear from @balos1 on this, but I think of `SUNContext_Free` as being more akin to `MPI_Finalize`, in that as with all other MPI functions it returns a success/failure flag (even though it's entirely clear how a user would "recover" from a failure in that routine).

**Comment by balos1** [comment]
> If the return value were to be non-zero, what are users supposed to do (e.g. retry freeing at some later point, leak the memory)?

What users do depends on their own application. E.g., some applications may want to call some sort of error handler and then exit. I can't provide any general answer on what a user should do other than that in most cases this would be an error that cannot be recovered from.  

POSIX `free` does not return a status code, [but it could set `errno`](https://stackoverflow.com/questions/30569981/does-free-set-errno). `SUNContext_Free` returns a status code instead of setting `errno` in case of an error. 

@drreynolds makes a nice comparison to what MPI does (return a code from all functions). The only caveat I'll add is that SUNDIALS is unfortunately inconsistent about this and does not return a code from all functions. Making our error handling and reporting more consistent is actually something we are working on right now.
