### ISSUE TITLE
Mixed precision CVODE

### ISSUE THREAD

**Issue by stgeke** [LLNL/sundials#274]
Are there any plans to support mixed precision in the near future? It would be interesting to have an option to perform the linear solve in reduced precision.

**Comment by drreynolds** [comment]
There is nothing keeping you from attempting this yourself.  CVODE allows users to supply a custom SUNLinearSolver object for use by the Newton nonlinear solver.  You could construct one using whatever mix of precision you would like to experiment with.

To answer your question, this is not on our current roadmap as a general-purpose option.  If you try this and it works well, please let us know, as those kinds of data points would be useful for planning future development.

**Comment by balos1** [comment]
We provide [an interface to the Ginkgo linear algebra library](https://sundials.readthedocs.io/en/latest/sunlinsol/SUNLinSol_links.html#the-sunlinearsolver-ginkgo-module) and Ginkgo does have some support for mixed-precision. I am not certain that our interface would allow you to use the mixed-precision solvers in Ginkgo (because I haven't tried), but I think it should be doable since we just take a Ginkgo linear solver object as-is.

**Comment by stgeke** [comment]
Is there an example how to use a custom SUNLinearSolver object?

**Comment by drreynolds** [comment]
* `examples/cvode/serial/cvAnalytic_mels.c`
* `examples/cvode/CXX_parhyp/cv_heat2D_hypre_ls.cpp`
* `examples/cvodes/serial/cvsAnalytic_mels.c`
* `examples/ida/serial/idaAnalytic_mels.c`
* `examples/arkode/CXX_parhyp/ark_heat2D_hypre_ls.cpp`
* `examples/arkode/C_serial/ark_analytic_mels.c`
* `examples/arkode/F2003_custom/fsunlinsol_fortran_mod.f90`
* `examples/idas/serial/idasAnalytic_mels.c`
