### ISSUE TITLE
SUNDIALS IDA Installation in Matlab

### ISSUE THREAD

**Issue by kimo707** [LLNL/sundials#305]
I am currently working on a project that requires the use of the Sundials solver in MATLAB. I have tried to find information about the installation process in the user guide, but unfortunately, I couldn't locate any relevant details.

I am writing to kindly request your assistance in providing me with the necessary information on how to install the Sundials solver on MATLAB. Any guidance or step-by-step instructions you can offer would be greatly appreciated.

If there are any specific prerequisites or system requirements I need to be aware of before installation, please do let me know. Additionally, if there are any compatibility issues with certain versions of MATLAB or Sundials, I would be grateful for that information as well.

**Comment by Steven-Roberts** [comment]
Hi @kimo707. SUNDIALS does not provide a MATLAB interface at this time. Is there a reason you can't use the built-in MATLAB function [`ode15i`](https://www.mathworks.com/help/matlab/ref/ode15i.html)? I'll note that [Octave](https://octave.org/), an open source MATLAB alternative, uses IDA for its implementation of `ode15s` and `ode15i`. Otherwise, you may need a third-party tool or custom mex files to call IDA from MATLAB.

Regarding installation and prerequisites, you can refer to https://sundials.readthedocs.io/en/latest/Install_link.html, but this is for use in C/C++/Fortran programs.

**Comment by Nelson-numerical-software** [comment]
Hi, 
mex interface was a great feature for others tools compatible (open source world). This allowed to propose sundials as it.
Currently I need to use old versions or rewrite a full implementation.
Thanks for your great works on Sundials

**Comment by balos1** [comment]
@Nelson-numerical-software I've noted that you're requesting a MATLAB interface to SUNDIALS. I cannot promise **if** or when this would be implemented.

**Comment by mottelet** [comment]
Next version of Scilab (2024.0 in october) will give access to almost all SUNDIALS solvers (idas will be interfaced later) and preview builds are available here: https://www.utc.fr/~mottelet/scilab_for_macOS.html. I have started porting the gateways code for Nelson a few month ago but I had to focus on Scilab release this spring and summer.

**Comment by Steven-Roberts** [comment]
FYI, the upcoming MATLAB release, 2024a, will provide IDAS and CVODES as solver options for an [`ode`](https://www.mathworks.com/help/releases/R2024a/matlab/ref/ode.html).

I'll close this issue unless folks have additional questions or comments.
