### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by ianabel** [LLNL/sundials#348]
In the 'NVECTOR_CUDA' documentation it is stated that 

"All vectors used in a single instance of a SUNDIALS package must use the same execution policy"

I have two questions -- 

1)  is this still a restriction on NVECTOR_CUDA? 

2) Is this a restriction also on custom NVECTORs backed by CUDA ? If not, perhaps the docs could be reworded to "All instances of NVECTOR_CUDA ... "

If this is also a restriction on custom NVECTORs then perhaps we can use this issue to discuss how hard relaxing this would be.

**Comment by drreynolds** [comment]
I believe that this is still in place, since SUNDIALS "clones" the template N_Vector (including its execution policy) to create internal integrator memory.

I also think that this is specific to the SUNDIALS-implemented vectors, but I'll defer to @balos1 on whether custom vectors can/should relax this.

**Comment by balos1** [comment]
This is still a restriction that we have in place for our SUNDIALS-implemented vectors. A custom vector (that uses CUDA or otherwise) does not have this constraint, and does not even need to use the execution policy objects. If I recall correctly, the reason that this restriction exists is to avoid having vectors that are used by the integrator running in different CUDA streams, which has the potential to cause synchronization problems within the integrator. A custom vector implementation should still be aware of this. If you setup execution policies with the same stream but different settings for block/threads sizes (for example), that probably would be fine now. 

With that said, we need to re-evaluate the use of streams within the GPU enabled SUNDIALS vectors. So, it would be great if you could share your use case for having different execution policies for different vectors.

**Comment by ianabel** [comment]
@bdorland will have more detailed description of the different execution policies, but its all about reshaping the thread/block size to optimize the different parts of the timestep (so inside the evaluation of the RHS function). For the custom NVECTOR operations all the thread/block sizes will most likely be the same.  

We do make use of some streams, but I expect that's all internal to the RHS evaluation and we would manually synchronize that ourselves.

**Comment by ianabel** [comment]
We also use device kernels to reduce the size of the diagnostic data we return to the host and then write to disk, those kernels almost always have a different thread/block dimension to the time-advance kernels. (this is another reason we'll be using a custom NVECTOR -- we don't store the full data on the host)

**Comment by balos1** [comment]
@ianabel If the multiple streams are within the RHS only, then that should not be a problem. I am interested in meeting to discuss this in more detail, I will send you an email to coordinate.
