### ISSUE TITLE
Check system installation of sundials

### ISSUE THREAD

**Issue by sn248** [LLNL/sundials#533]
Hi

I am trying to update the R interface to Sundials (sn248/sundialr). R package rules dictate that I first check for system installation of sundials before using the bundled-up version.

I was not able to find any information regarding pkg-config for sundials.

Could you suggest how to check if sundials is installed on user's machine?

Thanks

**Comment by balos1** [comment]
> I was not able to find any information regarding pkg-config for sundials.

We do not provide a pkg-config file at this time (see #242). 

> Could you suggest how to check if sundials is installed on user's machine?

CMake's `find_package` command is the supported way.  Not sure if this possible for you to use.

**Comment by sn248** [comment]
Thank you for the quick response. Could you provide the example command (sorry I am not very familiar with CMake)?

**Comment by balos1** [comment]
Sorry, I meant that the supported way is to use the `find_package` command from a `CMakeLists.txt`. According to the output of `cmake --help` though,  the `--find-package` command line option is deprecated (I have never used it either, so I am unsure if it can do what youre asking).

From a `CMakeLists.txt` you would do
```cmake
find_package(SUNDIALS)
```
Then the `SUNDIALS::<component>` targets would  give you the link libraries and include paths. See [this](https://sundials.readthedocs.io/en/latest/sundials/Install_link.html#using-sundials-as-a-third-party-library-in-other-cmake-projects) part of the docs.

Otherwise, you may need to write some custom script to look for sundials and then parse the SUNDIALSConfig.cmake / SUNDIALSTargets.cmake files to get the includes and link libraries. We have noted that a pkg-config file is a requested feature and hope to add it at some point in the future (we would also happily take a community contribution that does it).

**Comment by sn248** [comment]
Thanks again! This is helpful although I am not sure how to use a CMakelist.txt within R package to compile using system installation.

Perhaps, I will wait till we get a pkg-config, until then use the current approach of bundling the Sundials source with the package.

**Comment by balos1** [comment]
OK. I will close this now as a duplicate request for a pkg-config file.
