### ISSUE TITLE
Question regarding the parallel implementations fo NVector. 

### ISSUE THREAD

**Issue by CiaranWelsh** [LLNL/sundials#59]
Hello, 

I work in systems biology and I am updating the cvode library in our "roadrunner" library for modelling biological systems. I have a question regarding the parallel versions of NVector. In the docs, its stated that vectors should be of length at least 100K before the overhead of using pthread/openMP are worth the effort. In a typical model we use an NVector much smaller that this (think 10's to 100's), but we often need to integrate many times to estimate the parameters of these models. Is there a way we could benefit from the parallel implementations, or do we just incur overhead after every time we reset the system back to `t0`? Hopefully my questions is clear. 

Thanks, Ciaran

**Comment by drreynolds** [comment]
Hi Ciaran,

The comment in the documentation focuses on whether it is beneficial to use Pthreads/OpenMP when solving one large system of ODEs. It sounds like you have a different use case, that of solving an ensemble of ODEs with slight variations in parameters and/or initial conditions. Assuming that there is no dependence between these ODEs (i.e., that they could be run simultaneously), then it's likely that you could easily benefit from OpenMP. However, this threading would not occur within the N_Vector, since that would imply dependence between these separate ODEs, and a need to co-evolve them in lock step. Instead, you would want to use OpenMP at a higher level, where you create the OpenMP parallel region, and then inside that region you would have each thread separately allocate its own CVODE integrator memory structure, set up its own problem (that depends on the various initial conditions and parameters unique to that instance), and call CVODE to evolve the simulation. This type of approach should work natively from either the C or the new Fortran2003 APIs, as both are threadsafe.
Daniel R. Reynolds
Professor
214-768-4339 (tel:214-768-4339)
SMU Mathematics (https://link.getmailspring.com/link/4DBA75F2-FAC9-4BFF-B4AA-70C6492F0AC8@getmailspring.com/0?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3DSMU%2520Mathematics&recipient=cmVwbHkrQUMyVE9PUEVCVUlQV0FHTktKUVlaVE42SUlVVVpFVkJOSEhEQkdVWVBNQHJlcGx5LmdpdGh1Yi5jb20%3D)
http://faculty.smu.edu/reynolds (https://link.getmailspring.com/link/4DBA75F2-FAC9-4BFF-B4AA-70C6492F0AC8@getmailspring.com/1?redirect=http%3A%2F%2Ffaculty.smu.edu%2Freynolds&recipient=cmVwbHkrQUMyVE9PUEVCVUlQV0FHTktKUVlaVE42SUlVVVpFVkJOSEhEQkdVWVBNQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by CiaranWelsh** [comment]
Hi Daniel, I thought it'd be something like that - glad I checked. Thanks for the advice.
