### ISSUE TITLE
Question regarding choice of Newton solver in IDA

### ISSUE THREAD

**Issue by ianabel** [LLNL/sundials#594]
IDA provides a default Newton method (Modified Newton with no globalization) for solving the nonlinear algebraic system at every timestep. However, IDA also implements a Newton+Linesearch algorithm which is (as far as I can tell) only used from within IDACalcIC, and cannot be selected as the nonlinear solver for the per-timestep systems.

Is there a deep reason for not using linesearch globalization with the systems that IDA produces ? I am considering implementing a custom SUNNonlinearSolver to do some sort of parallelized Newton+LS and wondered if this was known to be a bad idea :)

**Comment by cswoodward** [comment]
Because IDA uses adaptive step sizes, there is a general assumption that steps will not be so large that globalization will be necessary with Newton's method.  If Newton fails with a low iteration count, IDA will cut the time step and recompute it.  Do you have a problem with excessive Newton iteration counts with IDA?
